<?php

/*----Create view tables*/

require("../Site/DBWarnMsg.php");
require("../Site/DBErrorMsg.php");

/*--------<VIEW EMPLOYEE TABLES>--------*/
$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_EMPLOYEE AS
SELECT
EMPLOYEE.EMPLOYEE_ID AS EMP_ID,
EMPLOYEE.EMPLOYEE_POSITION_ID AS EMP_POS_ID,
EMPLOYEE.COMPANY_ID AS EMP_COMP_ID,
EMPLOYEE.EMPLOYEE_DATA_ID AS EMP_DATA_ID,
EMPLOYEE.AVAILABLE_ID AS EMP_AVAIL,
EMPLOYEE.ACCESS_LEVEL_ID AS EMP_ACCESS,
EMPLOYEE.EMPLOYEE_CDate AS EMP_CDate
FROM
EMPLOYEE;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 1 " . $DBViewErrorMsg . $DBConn->GetError());

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_EMPLOYEE_LOGIN AS
SELECT
EMPLOYEE.EMPLOYEE_ID AS EMP_ID,
EMPLOYEE_DATA.EMPLOYEE_DATA_Email AS EMP_Email,
EMPLOYEE_DATA.EMPLOYEE_DATA_PassWord AS EMP_Pass,
EMPLOYEE.AVAILABLE_ID AS EMP_AVAIL,
EMPLOYEE.ACCESS_LEVEL_ID AS EMP_ACCESS,
EMPLOYEE.EMPLOYEE_CDate AS EMP_CDate
FROM
EMPLOYEE,
EMPLOYEE_DATA
WHERE
EMPLOYEE.EMPLOYEE_DATA_ID = EMPLOYEE_DATA.EMPLOYEE_DATA_ID;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 2 " . $DBViewErrorMsg . $DBConn->GetError());

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_EMPLOYEE_POSITION AS
SELECT
EMPLOYEE_POSITION.EMPLOYEE_POSITION_ID AS EMP_ID,
EMPLOYEE_POSITION.ACCESS_LEVEL_ID AS EMP_ACCESS,
EMPLOYEE_POSITION.AVAILABLE_ID AS EMP_AVAIL,
EMPLOYEE_POSITION.EMPLOYEE_POSITION_Title AS EMP_Title,
EMPLOYEE_POSITION.EMPLOYEE_POSITION_CDate AS EMP_CDate
FROM
EMPLOYEE_POSITION;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 3 " . $DBViewErrorMsg . $DBConn->GetError());

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_EMPLOYEE_DATA AS
SELECT
EMPLOYEE_DATA.EMPLOYEE_DATA_ID AS EMP_ID,
EMPLOYEE_DATA.ACCESS_LEVEL_ID AS EMP_ACCESS,
EMPLOYEE_DATA.AVAILABLE_ID AS EMP_AVAIL,
EMPLOYEE_DATA.EMPLOYEE_DATA_Salary AS EMP_Sal,
EMPLOYEE_DATA.EMPLOYEE_DATA_Name AS EMP_Name,
EMPLOYEE_DATA.EMPLOYEE_DATA_PassWord AS EMP_PassWord,
EMPLOYEE_DATA.EMPLOYEE_DATA_BDay AS EMP_BDay,
EMPLOYEE_DATA.EMPLOYEE_DATA_CDate AS EMP_CDate
FROM
EMPLOYEE_DATA;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 4 " . $DBViewErrorMsg . $DBConn->GetError());

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_EMPLOYEE_GENERAL AS
SELECT
EMPLOYEE.EMPLOYEE_ID AS EMP_ID,
EMPLOYEE.ACCESS_LEVEL_ID AS EMP_ACCESS,
EMPLOYEE_DATA.ACCESS_LEVEL_ID AS EMP_DATA_ACCESS,
EMPLOYEE_POSITION.ACCESS_LEVEL_ID AS EMP_POS_ACCESS,
EMPLOYEE.AVAILABLE_ID AS EMP_AVAIL,
EMPLOYEE_POSITION.AVAILABLE_ID AS EMP_AVAIL_POS,
EMPLOYEE_DATA.AVAILABLE_ID AS EMP_AVAIL_DATA,
EMPLOYEE_DATA.EMPLOYEE_DATA_Salary AS EMP_Sal,
EMPLOYEE_DATA.EMPLOYEE_DATA_Email AS EMP_Email,
EMPLOYEE_DATA.EMPLOYEE_DATA_Name AS EMP_Name,
EMPLOYEE_DATA.EMPLOYEE_DATA_PassWord AS EMP_PassWord,
EMPLOYEE_POSITION.EMPLOYEE_POSITION_Title AS EMP_Title,
EMPLOYEE_DATA.EMPLOYEE_DATA_BDay AS EMP_BDay
FROM
EMPLOYEE,
EMPLOYEE_DATA,
EMPLOYEE_POSITION
WHERE
EMPLOYEE_POSITION.EMPLOYEE_POSITION_ID = EMPLOYEE.EMPLOYEE_POSITION_ID
AND EMPLOYEE_DATA.EMPLOYEE_DATA_ID = EMPLOYEE.EMPLOYEE_DATA_ID;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 5 " . $DBViewErrorMsg . $DBConn->GetError());

/*--------<VIEW COUNTRY TABLES>--------*/
$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_COUNTRY AS
SELECT
COUNTRY.COUNTRY_ID AS COU_ID,
COUNTRY.ACCESS_LEVEL_ID AS COU_ACCESS,
COUNTRY.COUNTRY_DATA_ID AS COU_DATA_ID,
COUNTRY.AVAILABLE_ID AS COU_AVAIL,
COUNTRY.COUNTRY_CDate AS COU_CDate
FROM
COUNTRY;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 6 " . $DBViewErrorMsg . $DBConn->GetError());

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_COUNTRY_DATA AS
SELECT
COUNTRY_DATA.COUNTRY_DATA_ID AS COU_ID,
COUNTRY_DATA.ACCESS_LEVEL_ID AS COU_ACCESS,
COUNTRY_DATA.AVAILABLE_ID AS COU_AVAIL,
COUNTRY_DATA.COUNTRY_DATA_Title AS COU_Title,
COUNTRY_DATA.COUNTRY_DATA_Tax AS COU_Tax,
COUNTRY_DATA.COUNTRY_DATA_InterestRate AS COU_IR,
COUNTRY_DATA.COUNTRY_DATA_Date AS COU_Date,
COUNTRY_DATA.COUNTRY_DATA_CDate AS COU_CDate
FROM
COUNTRY_DATA;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 7 " . $DBViewErrorMsg . $DBConn->GetError());

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_COUNTRY_GENERAL AS
SELECT
COUNTRY.COUNTRY_ID AS COU_ID,
COUNTRY.ACCESS_LEVEL_ID AS COU_ACCESS,
COUNTRY_DATA.ACCESS_LEVEL_ID AS COU_DATA_ACCESS,
COUNTRY.AVAILABLE_ID AS COU_AVAIL,
COUNTRY_DATA.AVAILABLE_ID AS COU_DATA_AVAIL,
COUNTRY_DATA.COUNTRY_DATA_Title COU_Title,
COUNTRY_DATA.COUNTRY_DATA_Tax AS COU_Tax,
COUNTRY_DATA.COUNTRY_DATA_InterestRate AS COU_IR,
COUNTRY_DATA.COUNTRY_DATA_Date AS COU_Date,
COUNTRY.COUNTRY_CDate AS COU_CDate
FROM
COUNTRY,
COUNTRY_DATA
WHERE
COUNTRY.COUNTRY_DATA_ID = COUNTRY_DATA.COUNTRY_DATA_ID;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 8 " . $DBViewErrorMsg . $DBConn->GetError());

/*--------<VIEW JOB TABLES>--------*/
$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_JOB_ASSIGMENT AS
SELECT
JOB_ASSIGMENT.JOB_ASSIGMENT_ID AS JOB_ASS_ID,
JOB_ASSIGMENT.ACCESS_LEVEL_ID AS JOB_ACCESS,
JOB_ASSIGMENT.EMPLOYEE_ID AS EMP_ID,
JOB_ASSIGMENT.JOB_ID AS JOB_ID,
JOB_ASSIGMENT.AVAILABLE_ID AS JOB_AVAIL,
JOB_ASSIGMENT.JOB_ASSIGMENT_CDate AS JOB_CDate
FROM
JOB_ASSIGMENT;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 9 " . $DBViewErrorMsg . $DBConn->GetError());

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_JOB AS
SELECT
JOB.JOB_ID AS JOB_ID,
JOB.JOB_DATA_ID AS JOB_DATA_ID,
JOB.COMPANY_ID AS COMP_ID,
JOB.AVAILABLE_ID AS JOB_AVAIL,
JOB.JOB_Title AS JOB_Title,
JOB.ACCESS_LEVEL_ID AS JOB_ACCESS,
JOB.JOB_CDate AS JOB_CDate
FROM
JOB;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 10 " . $DBViewErrorMsg . $DBConn->GetError());

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_JOB_DATA AS
SELECT
JOB_DATA.JOB_DATA_ID AS JOB_ID,
JOB_DATA.ACCESS_LEVEL_ID AS JOB_ACCESS,
JOB_DATA.JOB_INCOME_ID AS JOB_INC_ID,
JOB_DATA.JOB_OUTCOME_ID AS JOB_OUT_ID,
JOB_DATA.AVAILABLE_ID AS JOB_AVAIL,
JOB_DATA.JOB_DATA_CDate AS JOB_CDate
FROM
JOB_DATA;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 11 " . $DBViewErrorMsg . $DBConn->GetError());

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_JOB_INCOME AS
SELECT
JOB_INCOME.JOB_INCOME_ID AS JOB_ID,
JOB_INCOME.ACCESS_LEVEL_ID AS JOB_ACCESS,
JOB_INCOME.AVAILABLE_ID AS JOB_AVAIL,
JOB_INCOME.JOB_INCOME_Price AS JOB_Price,
JOB_INCOME.JOB_INCOME_PIA AS JOB_PIA,
JOB_INCOME.JOB_INCOME_CDate AS JOB_CDate
FROM
JOB_INCOME;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 12 " . $DBViewErrorMsg . $DBConn->GetError());

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_JOB_OUTCOME AS
SELECT
JOB_OUTCOME.JOB_OUTCOME_ID AS JOB_ID,
JOB_OUTCOME.ACCESS_LEVEL_ID AS JOB_ACCESS,
JOB_OUTCOME.AVAILABLE_ID AS JOB_AVAIL,
JOB_OUTCOME.JOB_OUTCOME_Expenses AS JOB_Exp,
JOB_OUTCOME.JOB_OUTCOME_Damage AS JOB_Dam,
JOB_OUTCOME.JOB_OUTCOME_CDate AS JOB_CDate
FROM
JOB_OUTCOME;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 13 " . $DBViewErrorMsg . $DBConn->GetError());

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_JOB_INCOME_TIME AS
SELECT
JOB_INCOME_TIME.JOB_INCOME_TIME_ID AS JOB_ID,
JOB_INCOME_TIME.ACCESS_LEVEL_ID AS JOB_ACCESS,
JOB_INCOME_TIME.JOB_INCOME_ID AS JOB_INC_ID,
JOB_INCOME_TIME.AVAILABLE_ID AS JOB_AVAIL,
JOB_INCOME_TIME.JOB_INCOME_TIME_PIT AS JOB_PIT,
JOB_INCOME_TIME.JOB_INCOME_TIME_Date AS JOB_Date,
JOB_INCOME_TIME.JOB_INCOME_TIME_CDate AS JOB_CDate
FROM
JOB_INCOME_TIME;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 14 " . $DBViewErrorMsg . $DBConn->GetError());

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_JOB_GENERAL AS
SELECT
JOB.JOB_ID AS JOB_ID,
JOB_DATA.JOB_DATA_ID AS JOB_DATA_ID,
JOB_INCOME.JOB_INCOME_ID AS JOB_INC_ID,
JOB_OUTCOME.JOB_OUTCOME_ID AS JOB_OUT_ID,
JOB.ACCESS_LEVEL_ID AS JOB_ACCESS,
JOB_DATA.ACCESS_LEVEL_ID AS JOB_DATA_ACCESS,
JOB_OUTCOME.ACCESS_LEVEL_ID AS JOB_OUT_ACCESS,
JOB_INCOME.ACCESS_LEVEL_ID AS JOB_INC_ACCESS,
COMPANY.ACCESS_LEVEL_ID AS COMP_ACCESS,
COMPANY_DATA.ACCESS_LEVEL_ID AS COMP_DATA_ACCESS,
JOB.AVAILABLE_ID AS JOB_AVAIL,
JOB_DATA.AVAILABLE_ID AS JOB_DATA_AVAIL,
JOB_INCOME.AVAILABLE_ID AS JOB_INC_AVAIL,
JOB_OUTCOME.AVAILABLE_ID AS JOB_OUT_AVAIL,
COMPANY.AVAILABLE_ID AS COMP_AVAIL,
COMPANY_DATA.AVAILABLE_ID AS COMP_DATA_AVAIL,
COMPANY_DATA.COMPANY_DATA_Title AS COMP_Title,
COMPANY_DATA.COMPANY_DATA_Date As COMP_Date,
JOB_DATA.JOB_DATA_Date AS JOB_Date,
JOB_INCOME.JOB_INCOME_Price AS JOB_Price,
JOB_INCOME.JOB_INCOME_PIA AS JOB_PIA,
JOB_OUTCOME.JOB_OUTCOME_Expenses AS JOB_Exp,
JOB_OUTCOME.JOB_OUTCOME_Damage AS JOB_Dam
FROM
JOB,
JOB_DATA,
JOB_OUTCOME,
JOB_INCOME,
COMPANY,
COMPANY_DATA
WHERE
(COMPANY.COMPANY_DATA_ID = COMPANY_DATA.COMPANY_DATA_ID
AND JOB_DATA.JOB_OUTCOME_ID = JOB_OUTCOME.JOB_OUTCOME_ID
AND JOB_DATA.JOB_INCOME_ID = JOB_INCOME.JOB_INCOME_ID
AND JOB.JOB_DATA_ID = JOB_DATA.JOB_DATA_ID
AND JOB.COMPANY_ID = COMPANY.COMPANY_ID);";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 15 " . $DBViewErrorMsg . $DBConn->GetError());

/*--------<VIEW SHAREHOLDER TABLES>--------*/
$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_SHAREHOLDER AS
SELECT
SHAREHOLDER.SHAREHOLDER_ID AS SHARE_ID,
SHAREHOLDER.EMPLOYEE_ID AS EMP_ID,
SHAREHOLDER.ACCESS_LEVEL_ID AS SHARE_ACCESS,
SHAREHOLDER.AVAILABLE_ID AS SHARE_AVAIL
FROM
SHAREHOLDER;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 16 " . $DBViewErrorMsg . $DBConn->GetError());

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_SHAREHOLDER_GENERAL AS
SELECT
SHAREHOLDER.SHAREHOLDER_ID AS SHARE_ID,
SHAREHOLDER.EMPLOYEE_ID AS EMP_ID,
SHAREHOLDER.ACCESS_LEVEL_ID AS SHARE_ACCESS,
EMPLOYEE_DATA.ACCESS_LEVEL_ID AS EMP_DATA_ACCESS,
SHAREHOLDER.AVAILABLE_ID AS SHARE_AVAIL,
EMPLOYEE_DATA.AVAILABLE_ID AS EMP_AVAIL,
EMPLOYEE_POSITION.AVAILABLE_ID AS EMP_POS_AVAIL,
EMPLOYEE_DATA.EMPLOYEE_DATA_Salary AS EMP_Salary,
EMPLOYEE_DATA.EMPLOYEE_DATA_BDay AS EMP_BDay,
EMPLOYEE_DATA.EMPLOYEE_DATA_Name AS EMP_Name,
EMPLOYEE_POSITION.EMPLOYEE_POSITION_Title AS EMP_Title
FROM
SHAREHOLDER,
EMPLOYEE,
EMPLOYEE_POSITION,
EMPLOYEE_DATA
WHERE
(SHAREHOLDER.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID
AND EMPLOYEE.EMPLOYEE_DATA_ID = EMPLOYEE_DATA.EMPLOYEE_DATA_ID
AND EMPLOYEE.EMPLOYEE_POSITION_ID = EMPLOYEE_POSITION.EMPLOYEE_POSITION_ID);";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 17 " . $DBViewErrorMsg . $DBConn->GetError());

/*--------<VIEW COMPANY TABLES>--------*/
$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_COMPANY AS
SELECT
COMPANY.COMPANY_ID AS COMP_ID,
COMPANY.COMPANY_DATA_ID AS COMP_DATA_ID,
COMPANY.ACCESS_LEVEL_ID AS COMP_ACCESS,
COMPANY.AVAILABLE_ID AS COMP_AVAIL
FROM
COMPANY;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 18 " . $DBViewErrorMsg . $DBConn->GetError());

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_COMPANY_DATA AS
SELECT
COMPANY_DATA.COMPANY_DATA_ID AS COMP_ID,
COMPANY_DATA.COUNTRY_ID AS COU_ID,
COMPANY_DATA.ACCESS_LEVEL_ID AS COMP_ACCESS,
COMPANY_DATA.AVAILABLE_ID AS COMP_AVAIL,
COMPANY_DATA.COMPANY_DATA_Title AS COMP_Title,
COMPANY_DATA.COMPANY_DATA_Date AS COMP_Date
FROM
COMPANY_DATA;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 19 " . $DBViewErrorMsg . $DBConn->GetError());

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_COMPANY_GENERAL AS
SELECT
COMPANY.COMPANY_ID AS COMP_ID,
COMPANY_DATA.COMPANY_DATA_ID AS COMP_DATA_ID,
COMPANY_DATA.COUNTRY_ID AS COU_ID,
COMPANY_DATA.ACCESS_LEVEL_ID AS COMP_DATA_ACCESS,
COMPANY.ACCESS_LEVEL_ID AS COMP_ACCESS,
COMPANY_DATA.AVAILABLE_ID AS COMP_DATA_AVAIL,
COMPANY.AVAILABLE_ID AS COMP_AVAIL,
COMPANY_DATA.COMPANY_DATA_Title AS COMP_Title,
COMPANY_DATA.COMPANY_DATA_Date AS COMP_Date,
COUNTRY_DATA.COUNTRY_DATA_Title AS COU_Title,
COUNTRY_DATA.COUNTRY_DATA_Tax AS COU_Tax,
COUNTRY_DATA.COUNTRY_DATA_InterestRate AS COU_IR,
COUNTRY_DATA.COUNTRY_DATA_Date AS COU_Date
FROM
COMPANY,
COMPANY_DATA,
COUNTRY,
COUNTRY_DATA
WHERE
COMPANY.COMPANY_DATA_ID = COMPANY_DATA.COMPANY_DATA_ID
AND COMPANY_DATA.COUNTRY_ID = COUNTRY.COUNTRY_ID
AND COUNTRY_DATA.COUNTRY_DATA_ID = COUNTRY.COUNTRY_DATA_ID;";

$DBConn->ExecQuery($DBQuery);

if(!$DBConn->HasError())
	printf("<br>" . $DBViewSuccMsg);
else
	printf("<br>ERROR 20 " . $DBViewErrorMsg . $DBConn->GetError());
?>
