<?php

/*----Create view tables*/

/*--------<VIEW EMPLOYEE TABLES>--------*/
$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_EMPLOYEE AS
SELECT
EMPLOYEE.EMPLOYEE_ID AS EMP_ID,
EMPLOYEE.EMPLOYEE_POSITION_ID AS EMP_POS_ID,
EMPLOYEE.COMPANY_ID AS EMP_COMP_ID,
EMPLOYEE.EMPLOYEE_DATA_ID AS EMP_DATA_ID,
EMPLOYEE.ACCESS_LEVEL_ID AS EMP_ACCESS,
EMPLOYEE.EMPLOYEE_CDate AS EMP_CDate
FROM
EMPLOYEE
WHERE
EMPLOYEE.AVAILABLE_ID = 2;";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 1 - Error creating view: " . $DBConn->error);

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_EMPLOYEE_POSITION AS
SELECT
EMPLOYEE_POSITION.EMPLOYEE_POSITION_ID AS EMP_ID,
EMPLOYEE_POSITION.ACCESS_LEVEL_ID AS EMP_ACCESS,
EMPLOYEE_POSITION.EMPLOYEE_POSITION_Title AS EMP_Title,
EMPLOYEE_POSITION.EMPLOYEE_POSITION_CDate AS EMP_CDate
FROM
EMPLOYEE_POSITION
WHERE
EMPLOYEE_POSITION.AVAILABLE_ID = 2;";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 2 - Error creating view: " . $DBConn->error);

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_EMPLOYEE_DATA AS
SELECT
EMPLOYEE_DATA.EMPLOYEE_DATA_ID AS EMP_ID,
EMPLOYEE_DATA.ACCESS_LEVEL_ID AS EMP_ACCESS,
EMPLOYEE_DATA.EMPLOYEE_DATA_Salary AS EMP_Sal,
EMPLOYEE_DATA.EMPLOYEE_DATA_Name AS EMP_Name,
EMPLOYEE_DATA.EMPLOYEE_DATA_PassWord AS EMP_PassWord,
EMPLOYEE_DATA.EMPLOYEE_DATA_BDay AS EMP_BDay,
EMPLOYEE_DATA.EMPLOYEE_DATA_CDate AS EMP_CDate
FROM
EMPLOYEE_DATA
WHERE
EMPLOYEE_DATA.AVAILABLE_ID = 2;";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 3 - Error creating view: " . $DBConn->error);

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_EMPLOYEE_GENERAL AS
SELECT
EMPLOYEE.EMPLOYEE_ID AS EMP_ID,
EMPLOYEE.ACCESS_LEVEL_ID AS EMP_ACCESS,
EMPLOYEE_DATA.ACCESS_LEVEL_ID AS EMP_DATA_ACCESS,
EMPLOYEE_POSITION.ACCESS_LEVEL_ID AS EMP_POS_ACCESS,
EMPLOYEE_DATA.EMPLOYEE_DATA_Salary AS EMP_Sal,
EMPLOYEE_DATA.EMPLOYEE_DATA_Name AS EMP_Name,
EMPLOYEE_DATA.EMPLOYEE_DATA_PassWord AS EMP_PassWord,
EMPLOYEE_POSITION.EMPLOYEE_POSITION_Title AS EMP_Title,
EMPLOYEE_DATA.EMPLOYEE_DATA_BDay AS EMP_BDay
FROM
EMPLOYEE,
EMPLOYEE_DATA,
EMPLOYEE_POSITION
WHERE
EMPLOYEE_POSITION.EMPLOYEE_POSITION_ID = EMPLOYEE.EMPLOYEE_POSITION_ID
AND EMPLOYEE_DATA.EMPLOYEE_DATA_ID = EMPLOYEE.EMPLOYEE_DATA_ID
AND (EMPLOYEE.AVAILABLE_ID = 2
AND EMPLOYEE_DATA.AVAILABLE_ID = 2
AND EMPLOYEE_POSITION.AVAILABLE_ID = 2);";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 4 - Error creating view: " . $DBConn->error);

/*--------<VIEW COUNTRY TABLES>--------*/
$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_COUNTRY AS
SELECT
COUNTRY.COUNTRY_ID AS COU_ID,
COUNTRY.ACCESS_LEVEL_ID AS COU_ACCESS,
COUNTRY.COUNTRY_DATA_ID AS COU_DATA_ID,
COUNTRY.COUNTRY_CDate AS COU_CDate
FROM
COUNTRY
WHERE
COUNTRY.AVAILABLE_ID = 2;";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 5 - Error creating view: " . $DBConn->error);

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_COUNTRY_DATA AS
SELECT
COUNTRY_DATA.COUNTRY_DATA_ID AS COU_ID,
COUNTRY_DATA.ACCESS_LEVEL_ID AS COU_ACCESS,
COUNTRY_DATA.COUNTRY_DATA_Title AS COU_Title,
COUNTRY_DATA.COUNTRY_DATA_Tax AS COU_Tax,
COUNTRY_DATA.COUNTRY_DATA_InterestRate AS COU_IR,
COUNTRY_DATA.COUNTRY_DATA_Date AS COU_Date,
COUNTRY_DATA.COUNTRY_DATA_CDate AS COU_CDate
FROM
COUNTRY_DATA
WHERE
COUNTRY_DATA.AVAILABLE_ID = 2;";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 6 - Error creating view: " . $DBConn->error);

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_COUNTRY_GENERAL AS
SELECT
COUNTRY.COUNTRY_ID AS COU_ID,
COUNTRY.ACCESS_LEVEL_ID AS COU_ACCESS,
COUNTRY_DATA.ACCESS_LEVEL_ID AS COU_DATA_ACCESS,
COUNTRY_DATA.COUNTRY_DATA_Title COU_Title,
COUNTRY_DATA.COUNTRY_DATA_Tax AS COU_Tax,
COUNTRY_DATA.COUNTRY_DATA_InterestRate AS COU_IR,
COUNTRY_DATA.COUNTRY_DATA_Date AS COU_Date,
COUNTRY.COUNTRY_CDate AS COU_CDate
FROM
COUNTRY,
COUNTRY_DATA
WHERE
COUNTRY.COUNTRY_DATA_ID = COUNTRY_DATA.COUNTRY_DATA_ID
AND (COUNTRY.AVAILABLE_ID = 2 AND COUNTRY_DATA.AVAILABLE_ID = 2);";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 7 - Error creating view: " . $DBConn->error);

/*--------<VIEW JOB TABLES>--------*/
$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_JOB_ASSIGMENT AS
SELECT
JOB_ASSIGMENT.JOB_ASSIGMENT_ID AS JOB_ASS_ID,
JOB_ASSIGMENT.ACCESS_LEVEL_ID AS JOB_ACCESS,
JOB_ASSIGMENT.EMPLOYEE_ID AS EMP_ID,
JOB_ASSIGMENT.JOB_ID AS JOB_ID,
JOB_ASSIGMENT.JOB_ASSIGMENT_CDate AS JOB_CDate
FROM
JOB_ASSIGMENT
WHERE
JOB_ASSIGMENT.AVAILABLE_ID = 2;";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 8 - Error creating view: " . $DBConn->error);

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_JOB AS
SELECT
JOB.JOB_ID AS JOB_ID,
JOB.JOB_Title AS JOB_Title,
JOB.ACCESS_LEVEL_ID AS JOB_ACCESS,
JOB.JOB_DATA_ID AS JOB_DATA_ID,
JOB.COMPANY_ID AS COMP_ID,
JOB.JOB_CDate AS JOB_CDate
FROM
JOB
WHERE
JOB.AVAILABLE_ID = 2;";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 9 - Error creating view: " . $DBConn->error);

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_JOB_DATA AS
SELECT
JOB_DATA.JOB_DATA_ID AS JOB_ID,
JOB_DATA.ACCESS_LEVEL_ID AS JOB_ACCESS,
JOB_DATA.JOB_INCOME_ID AS JOB_INC_ID,
JOB_DATA.JOB_OUTCOME_ID AS JOB_OUT_ID,
JOB_DATA.JOB_DATA_CDate AS JOB_CDate
FROM
JOB_DATA
WHERE
JOB_DATA.AVAILABLE_ID = 2;";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 10 - Error creating view: " . $DBConn->error);

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_JOB_INCOME AS
SELECT
JOB_INCOME.JOB_INCOME_ID AS JOB_ID,
JOB_INCOME.ACCESS_LEVEL_ID AS JOB_ACCESS,
JOB_INCOME.JOB_INCOME_Price AS JOB_Price,
JOB_INCOME.JOB_INCOME_PIA AS JOB_PIA,
JOB_INCOME.JOB_INCOME_CDate AS JOB_CDate
FROM
JOB_INCOME
WHERE
JOB_INCOME.AVAILABLE_ID = 2;";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 11 - Error creating view: " . $DBConn->error);

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_JOB_OUTCOME AS
SELECT
JOB_OUTCOME.JOB_OUTCOME_ID AS JOB_ID,
JOB_OUTCOME.ACCESS_LEVEL_ID AS JOB_ACCESS,
JOB_OUTCOME.JOB_OUTCOME_Expenses AS JOB_Expenses,
JOB_OUTCOME.JOB_OUTCOME_Damage AS JOB_Damage,
JOB_OUTCOME.JOB_OUTCOME_CDate AS JOB_CDate
FROM
JOB_OUTCOME
WHERE
JOB_OUTCOME.AVAILABLE_ID = 2;";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 12 - Error creating view: " . $DBConn->error);

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_JOB_INCOME_TIME AS
SELECT
JOB_INCOME_TIME.JOB_INCOME_TIME_ID AS JOB_ID,
JOB_INCOME_TIME.ACCESS_LEVEL_ID AS JOB_ACCESS,
JOB_INCOME_TIME.JOB_INCOME_ID AS JOB_INC_ID,
JOB_INCOME_TIME.JOB_INCOME_TIME_PIT AS JOB_PIT,
JOB_INCOME_TIME.JOB_INCOME_TIME_Date AS JOB_Date,
JOB_INCOME_TIME.JOB_INCOME_TIME_CDate AS JOB_CDate
FROM
JOB_INCOME_TIME
WHERE
JOB_INCOME_TIME.AVAILABLE_ID = 2;";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 13 - Error creating view: " . $DBConn->error);

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_JOB_GENERAL AS
SELECT
JOB.JOB_ID AS JOB_ID,
JOB_DATA.JOB_DATA_ID AS JOB_DATA_ID,
JOB_INCOME.JOB_INCOME_ID AS JOB_INC_ID,
JOB_OUTCOME.JOB_OUTCOME_ID AS JOB_OUT_ID,
JOB.ACCESS_LEVEL_ID AS JOB_ACCESS,
JOB_DATA.ACCESS_LEVEL_ID AS JOB_DATA_ACCESS,
JOB_OUTCOME.ACCESS_LEVEL_ID AS JOB_OUT_ACCESS,
JOB_INCOME.ACCESS_LEVEL_ID AS JOB_INC_ACCESS,
COMPANY.ACCESS_LEVEL_ID AS COMP_ACCESS,
COMPANY_DATA.ACCESS_LEVEL_ID AS COMP_DATA_ACCESS,
COMPANY_DATA.COMPANY_DATA_Title AS COMP_Title,
COMPANY_DATA.COMPANY_DATA_Date As COMP_Date,
JOB_DATA.JOB_DATA_Date AS JOB_Date,
JOB_INCOME.JOB_INCOME_Price AS JOB_Price,
JOB_INCOME.JOB_INCOME_PIA AS JOB_PIA,
JOB_OUTCOME.JOB_OUTCOME_Expenses AS JOB_Expenses,
JOB_OUTCOME.JOB_OUTCOME_Damage AS JOB_Damage
FROM
JOB,
JOB_DATA,
JOB_OUTCOME,
JOB_INCOME,
COMPANY,
COMPANY_DATA
WHERE
(JOB.AVAILABLE_ID = 2
AND JOB_DATA.AVAILABLE_ID = 2
AND JOB_OUTCOME.AVAILABLE_ID = 2
AND JOB_INCOME.AVAILABLE_ID = 2)
AND
(COMPANY.COMPANY_DATA_ID = COMPANY_DATA.COMPANY_DATA_ID
AND JOB_DATA.JOB_OUTCOME_ID = JOB_OUTCOME.JOB_OUTCOME_ID
AND JOB_DATA.JOB_INCOME_ID = JOB_INCOME.JOB_INCOME_ID
AND JOB.JOB_DATA_ID = JOB_DATA.JOB_DATA_ID
AND JOB.COMPANY_ID = COMPANY.COMPANY_ID);";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 14 - Error creating view: " . $DBConn->error);

/*--------<VIEW SHAREHOLDER TABLES>--------*/
$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_SHAREHOLDER AS
SELECT
SHAREHOLDER.SHAREHOLDER_ID AS SHARE_ID,
SHAREHOLDER.EMPLOYEE_ID AS EMP_ID,
SHAREHOLDER.ACCESS_LEVEL_ID AS SHARE_ACCESS
FROM
SHAREHOLDER
WHERE
SHAREHOLDER.AVAILABLE_ID = 2;";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 15 - Error creating view: " . $DBConn->error);

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_SHAREHOLDER_GENERAL AS
SELECT
SHAREHOLDER.SHAREHOLDER_ID AS SHARE_ID,
SHAREHOLDER.EMPLOYEE_ID AS EMP_ID,
SHAREHOLDER.ACCESS_LEVEL_ID AS SHARE_ACCESS,
EMPLOYEE_DATA.ACCESS_LEVEL_ID AS EMP_DATA_ACCESS,
EMPLOYEE_DATA.EMPLOYEE_DATA_Salary AS EMP_Salary,
EMPLOYEE_DATA.EMPLOYEE_DATA_BDay AS EMP_BDay,
EMPLOYEE_DATA.EMPLOYEE_DATA_Name AS EMP_Name,
EMPLOYEE_POSITION.EMPLOYEE_POSITION_Title AS EMP_Title
FROM
SHAREHOLDER,
EMPLOYEE,
EMPLOYEE_POSITION,
EMPLOYEE_DATA
WHERE
(SHAREHOLDER.AVAILABLE_ID = 2
AND EMPLOYEE_DATA.AVAILABLE_ID = 2)
AND
(SHAREHOLDER.EMPLOYEE_ID = EMPLOYEE.EMPLOYEE_ID
AND EMPLOYEE.EMPLOYEE_DATA_ID = EMPLOYEE_DATA.EMPLOYEE_DATA_ID
AND EMPLOYEE.EMPLOYEE_POSITION_ID = EMPLOYEE_POSITION.EMPLOYEE_POSITION_ID);";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 16 - Error creating view: " . $DBConn->error);

/*--------<VIEW COMPANY TABLES>--------*/
$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_COMPANY AS
SELECT
COMPANY.COMPANY_ID AS COMP_ID,
COMPANY.COMPANY_DATA_ID AS COMP_DATA_ID,
COMPANY.ACCESS_LEVEL_ID AS COMP_ACCESS
FROM
COMPANY
WHERE COMPANY.AVAILABLE_ID = 2;";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 17 - Error creating view: " . $DBConn->error);

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_COMPANY_DATA AS
SELECT
COMPANY_DATA.COMPANY_DATA_ID AS COMP_ID,
COMPANY_DATA.ACCESS_LEVEL_ID AS COMP_ACCESS,
COMPANY_DATA.COMPANY_DATA_Title AS COMP_Title,
COMPANY_DATA.COMPANY_DATA_Date AS COMP_Date,
COMPANY_DATA.COUNTRY_ID AS COU_ID
FROM
COMPANY_DATA
WHERE COMPANY_DATA.AVAILABLE_ID = 2;";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 18 - Error creating view: " . $DBConn->error);

$DBQuery="CREATE ALGORITHM = MERGE VIEW VIEW_COMPANY_GENERAL AS
SELECT
COMPANY.COMPANY_ID AS COMP_ID,
COMPANY_DATA.COMPANY_DATA_ID AS COMP_DATA_ID,
COMPANY_DATA.ACCESS_LEVEL_ID AS COMP_DATA_ACCESS,
COMPANY.ACCESS_LEVEL_ID AS COMP_ACCESS,
COMPANY_DATA.COMPANY_DATA_Title AS COMP_Title,
COMPANY_DATA.COMPANY_DATA_Date AS COMP_Date,
COMPANY_DATA.COUNTRY_ID AS COU_ID
FROM
COMPANY,
COMPANY_DATA
WHERE
(COMPANY.AVAILABLE_ID = 2
AND COMPANY_DATA.AVAILABLE_ID = 2);";

if($DBConn->query($DBQuery) === TRUE)
	printf("<br>View successfuly created");
else
	printf("<br>ERROR 19 - Error creating view: " . $DBConn->error);


?>
